#ifndef __TAKT_RISCV_ESP32C3_PORT_H__
#define __TAKT_RISCV_ESP32C3_PORT_H__

#define TAKT_INTR_FROM_CPU0_REG   0x600C0014u
#define TAKT_INTR_FROM_CPU0_BIT   0x1u

#define TAKT_RISCV_STACK_GUARD_ALIGN       32u
#define TAKT_RISCV_THREAD_INIT_FRAME_SIZE  128u
#define TAKT_RISCV_THREAD_INIT_ALIGN_SLACK 15u

#define TAKT_RISCV_PORT_DECLARE_START_FIRST 1
#define TAKT_RISCV_PORT_DECLARE_TICK_HANDLER 1

#define TAKT_RISCV_PORT_CTX_SWITCH_TRIGGER() \
    (*((volatile uint32_t*)TAKT_INTR_FROM_CPU0_REG) = TAKT_INTR_FROM_CPU0_BIT)

#endif // __TAKT_RISCV_ESP32C3_PORT_H__
